/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.BoardingPayoutsConfigurationsAcquirer = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BoardingPayoutsConfigurationsAcquirer model module.
   * @module model/BoardingPayoutsConfigurationsAcquirer
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>BoardingPayoutsConfigurationsAcquirer</code>.
   * @alias module:model/BoardingPayoutsConfigurationsAcquirer
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>BoardingPayoutsConfigurationsAcquirer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoardingPayoutsConfigurationsAcquirer} obj Optional instance to populate.
   * @return {module:model/BoardingPayoutsConfigurationsAcquirer} The populated <code>BoardingPayoutsConfigurationsAcquirer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('acquiringId')) {
        obj['acquiringId'] = ApiClient.convertToType(data['acquiringId'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
    }
    return obj;
  }

  /**
   * This code identifies the financial institution acting as the acquirer.  Also known as:  - Acquiring BIN - Acquiring Institution Identification Code 
   * @member {String} acquiringId
   */
  exports.prototype['acquiringId'] = undefined;
  /**
   * The acquirer's  [ISO 3166-1](https://developer.cybersource.com/docs/cybs/en-us/country-codes/reference/all/na/country-codes/country-codes.html) alpha-2 country code.  Possible values: - US - AF - AX - AL - DZ - AD - AO - AI - AQ - AG - AR - AM - AW - AU - AS - AT - AZ - BS - BH - BD - BB - BY - BE - BZ - BJ - BM - BT - BO - BA - BQ - BW - BV - BR - IO - VG - BN - BG - BF - BI - KH - CM - CA - CV - CW - KY - CF - TD - CL - CN - CX - CC - CO - KM - CD - CG - CK - CR - CI - HR - CU - CY - CZ - DK - DJ - DM - DO - EC - EG - SV - GQ - ER - EE - ET - FK - FO - FJ - FI - FR - GF - PF - TF - GA - GM - GE - DE - GH - GI - GR - GL - GD - GP - GU - GT - GG - GN - GW - GY - HT - HM - HN - HK - HU - IS - IN - ID - IR - IQ - IE - IM - IL - IT - JM - JP - JE - JO - KZ - KE - KI - KW - KG - LA - LV - LB - LS - LR - LY - LI - LT - LU - MO - MK - MG - MW - MY - MV - ML - MT - MH - MQ - MR - MU - YT - MX - FM - MD - MC - MN - ME - MS - MA - MZ - MM - NA - NR - NP - NL - AN - NC - NZ - NI - NE - NG - NU - NF - KP - MP - NO - OM - PK - PW - PS - PA - PG - PY - PE - PH - PN - PL - PT - PR - QA - RE - RO - RU - RW - BL - SH - KN - LC - MF - PM - VC - WS - SM - SS - ST - SX - SA - SN - RS - SC - SL - SG - SK - SI - SB - SO - ZA - GS - KR - ES - LK - SD - SR - SJ - SZ - SE - CH - SY - TW - TJ - TZ - TH - TL - TG - TK - TO - TT - TN - TR - TM - TC - TV - UG - UA - AE - GB - UM - UY - UZ - VU - VA - VE - VN - VI - WF - KV - EH - YE - ZM - ZW
   * @member {String} country
   */
  exports.prototype['country'] = undefined;



  return exports;
}));


