/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Iccv1instructionsinstructionIdconfirmationsMerchantInformation', 'model/Iccv1instructionsinstructionIdconfirmationsOrderInformation', 'model/Iccv1instructionsinstructionIdconfirmationsProcessorInformation', 'model/Iccv1instructionsinstructionIdcredentialsClientReferenceInformation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Iccv1instructionsinstructionIdconfirmationsMerchantInformation'), require('./Iccv1instructionsinstructionIdconfirmationsOrderInformation'), require('./Iccv1instructionsinstructionIdconfirmationsProcessorInformation'), require('./Iccv1instructionsinstructionIdcredentialsClientReferenceInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Iccv1instructionsinstructionIdconfirmationsConfirmationData = factory(root.CyberSource.ApiClient, root.CyberSource.Iccv1instructionsinstructionIdconfirmationsMerchantInformation, root.CyberSource.Iccv1instructionsinstructionIdconfirmationsOrderInformation, root.CyberSource.Iccv1instructionsinstructionIdconfirmationsProcessorInformation, root.CyberSource.Iccv1instructionsinstructionIdcredentialsClientReferenceInformation);
  }
}(this, function(ApiClient, Iccv1instructionsinstructionIdconfirmationsMerchantInformation, Iccv1instructionsinstructionIdconfirmationsOrderInformation, Iccv1instructionsinstructionIdconfirmationsProcessorInformation, Iccv1instructionsinstructionIdcredentialsClientReferenceInformation) {
  'use strict';




  /**
   * The Iccv1instructionsinstructionIdconfirmationsConfirmationData model module.
   * @module model/Iccv1instructionsinstructionIdconfirmationsConfirmationData
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Iccv1instructionsinstructionIdconfirmationsConfirmationData</code>.
   * @alias module:model/Iccv1instructionsinstructionIdconfirmationsConfirmationData
   * @class
   * @param clientReferenceInformation {module:model/Iccv1instructionsinstructionIdcredentialsClientReferenceInformation} 
   * @param processorInformation {module:model/Iccv1instructionsinstructionIdconfirmationsProcessorInformation} 
   */
  var exports = function(clientReferenceInformation, processorInformation) {
    var _this = this;

    _this['clientReferenceInformation'] = clientReferenceInformation;


    _this['processorInformation'] = processorInformation;
  };

  /**
   * Constructs a <code>Iccv1instructionsinstructionIdconfirmationsConfirmationData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Iccv1instructionsinstructionIdconfirmationsConfirmationData} obj Optional instance to populate.
   * @return {module:model/Iccv1instructionsinstructionIdconfirmationsConfirmationData} The populated <code>Iccv1instructionsinstructionIdconfirmationsConfirmationData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('clientReferenceInformation')) {
        obj['clientReferenceInformation'] = Iccv1instructionsinstructionIdcredentialsClientReferenceInformation.constructFromObject(data['clientReferenceInformation']);
      }
      if (data.hasOwnProperty('orderInformation')) {
        obj['orderInformation'] = Iccv1instructionsinstructionIdconfirmationsOrderInformation.constructFromObject(data['orderInformation']);
      }
      if (data.hasOwnProperty('merchantInformation')) {
        obj['merchantInformation'] = Iccv1instructionsinstructionIdconfirmationsMerchantInformation.constructFromObject(data['merchantInformation']);
      }
      if (data.hasOwnProperty('processorInformation')) {
        obj['processorInformation'] = Iccv1instructionsinstructionIdconfirmationsProcessorInformation.constructFromObject(data['processorInformation']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Iccv1instructionsinstructionIdcredentialsClientReferenceInformation} clientReferenceInformation
   */
  exports.prototype['clientReferenceInformation'] = undefined;
  /**
   * @member {module:model/Iccv1instructionsinstructionIdconfirmationsOrderInformation} orderInformation
   */
  exports.prototype['orderInformation'] = undefined;
  /**
   * @member {module:model/Iccv1instructionsinstructionIdconfirmationsMerchantInformation} merchantInformation
   */
  exports.prototype['merchantInformation'] = undefined;
  /**
   * @member {module:model/Iccv1instructionsinstructionIdconfirmationsProcessorInformation} processorInformation
   */
  exports.prototype['processorInformation'] = undefined;



  return exports;
}));


