/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Iccv1agentsKeys = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Iccv1agentsKeys model module.
   * @module model/Iccv1agentsKeys
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Iccv1agentsKeys</code>.
   * Request object for uploading a new public key for an agent.
   * @alias module:model/Iccv1agentsKeys
   * @class
   * @param keyName {String} Unique name for this key within the agent. Must be unique per agent.
   * @param publicKey {String} Base64-encoded public key. Supported formats are PEM (PKCS#8 or PKCS#1) and JWK.
   * @param algorithm {String} HTTP Signature signing algorithm (RFC 9421 §3.3 registry). Must match the key type and curve:  - ***rsa-pss-sha256*** — RSA-PSS with SHA-256  - ***rsa-pss-sha512*** — RSA-PSS with SHA-512  - ***ecdsa-p256-sha256*** — ECDSA on P-256 curve with SHA-256  - ***ecdsa-p384-sha384*** — ECDSA on P-384 curve with SHA-384  - ***ed25519*** — EdDSA on Curve25519   Possible values: - rsa-pss-sha256 - rsa-pss-sha512 - ecdsa-p256-sha256 - ecdsa-p384-sha384 - ed25519
   */
  var exports = function(keyName, publicKey, algorithm) {
    var _this = this;

    _this['keyName'] = keyName;
    _this['publicKey'] = publicKey;
    _this['algorithm'] = algorithm;

  };

  /**
   * Constructs a <code>Iccv1agentsKeys</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Iccv1agentsKeys} obj Optional instance to populate.
   * @return {module:model/Iccv1agentsKeys} The populated <code>Iccv1agentsKeys</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('keyName')) {
        obj['keyName'] = ApiClient.convertToType(data['keyName'], 'String');
      }
      if (data.hasOwnProperty('publicKey')) {
        obj['publicKey'] = ApiClient.convertToType(data['publicKey'], 'String');
      }
      if (data.hasOwnProperty('algorithm')) {
        obj['algorithm'] = ApiClient.convertToType(data['algorithm'], 'String');
      }
      if (data.hasOwnProperty('expirationDate')) {
        obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Unique name for this key within the agent. Must be unique per agent.
   * @member {String} keyName
   */
  exports.prototype['keyName'] = undefined;
  /**
   * Base64-encoded public key. Supported formats are PEM (PKCS#8 or PKCS#1) and JWK.
   * @member {String} publicKey
   */
  exports.prototype['publicKey'] = undefined;
  /**
   * HTTP Signature signing algorithm (RFC 9421 §3.3 registry). Must match the key type and curve:  - ***rsa-pss-sha256*** — RSA-PSS with SHA-256  - ***rsa-pss-sha512*** — RSA-PSS with SHA-512  - ***ecdsa-p256-sha256*** — ECDSA on P-256 curve with SHA-256  - ***ecdsa-p384-sha384*** — ECDSA on P-384 curve with SHA-384  - ***ed25519*** — EdDSA on Curve25519   Possible values: - rsa-pss-sha256 - rsa-pss-sha512 - ecdsa-p256-sha256 - ecdsa-p384-sha384 - ed25519
   * @member {String} algorithm
   */
  exports.prototype['algorithm'] = undefined;
  /**
   * Key expiration date-time in UTC. Defaults to 14 days from registration if omitted.
   * @member {Date} expirationDate
   */
  exports.prototype['expirationDate'] = undefined;



  return exports;
}));


