/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Iccv1checkoutsessionsDiscountsAllocations = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Iccv1checkoutsessionsDiscountsAllocations model module.
   * @module model/Iccv1checkoutsessionsDiscountsAllocations
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Iccv1checkoutsessionsDiscountsAllocations</code>.
   * How a discount amount is allocated to a specific item or cart path.
   * @alias module:model/Iccv1checkoutsessionsDiscountsAllocations
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Iccv1checkoutsessionsDiscountsAllocations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Iccv1checkoutsessionsDiscountsAllocations} obj Optional instance to populate.
   * @return {module:model/Iccv1checkoutsessionsDiscountsAllocations} The populated <code>Iccv1checkoutsessionsDiscountsAllocations</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * JSONPath identifying the item this allocation applies to.
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * Discount amount allocated to this path, in cents.
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;



  return exports;
}));


