/**
 * CyberSource Flex API
 * Simple PAN tokenization service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2002PaymentInformationCard', 'model/InlineResponse2002PaymentInformationTokenizedCard'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2002PaymentInformationCard'), require('./InlineResponse2002PaymentInformationTokenizedCard'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.InlineResponse2002PaymentInformation = factory(root.CyberSource.ApiClient, root.CyberSource.InlineResponse2002PaymentInformationCard, root.CyberSource.InlineResponse2002PaymentInformationTokenizedCard);
  }
}(this, function(ApiClient, InlineResponse2002PaymentInformationCard, InlineResponse2002PaymentInformationTokenizedCard) {
  'use strict';




  /**
   * The InlineResponse2002PaymentInformation model module.
   * @module model/InlineResponse2002PaymentInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse2002PaymentInformation</code>.
   * @alias module:model/InlineResponse2002PaymentInformation
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse2002PaymentInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002PaymentInformation} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002PaymentInformation} The populated <code>InlineResponse2002PaymentInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('card')) {
        obj['card'] = InlineResponse2002PaymentInformationCard.constructFromObject(data['card']);
      }
      if (data.hasOwnProperty('tokenizedCard')) {
        obj['tokenizedCard'] = InlineResponse2002PaymentInformationTokenizedCard.constructFromObject(data['tokenizedCard']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse2002PaymentInformationCard} card
   */
  exports.prototype['card'] = undefined;
  /**
   * @member {module:model/InlineResponse2002PaymentInformationTokenizedCard} tokenizedCard
   */
  exports.prototype['tokenizedCard'] = undefined;



  return exports;
}));


