/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PushFunds400ResponseDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PushFunds400ResponseDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.InlineResponse40010 = factory(root.CyberSource.ApiClient, root.CyberSource.PushFunds400ResponseDetails);
  }
}(this, function(ApiClient, PushFunds400ResponseDetails) {
  'use strict';




  /**
   * The InlineResponse40010 model module.
   * @module model/InlineResponse40010
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse40010</code>.
   * @alias module:model/InlineResponse40010
   * @class
   * @param id {String} Request ID generated by Cybersource. This was sent in the header on the request. Echo value from x-requestid 
   * @param submitTimeUtc {String} Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`  **Example** `2023-05-17T22:47:57Z` equals May 17, 2023, at 22:47:57 (10:47:57 PM). The `T` separates the date and the time. The `Z` indicates UTC. 
   * @param status {String} Message describing the status of the currency conversion request.   Possible values: - INVALID_REQUEST
   */
  var exports = function(id, submitTimeUtc, status) {
    var _this = this;

    _this['id'] = id;
    _this['submitTimeUtc'] = submitTimeUtc;
    _this['status'] = status;



  };

  /**
   * Constructs a <code>InlineResponse40010</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse40010} obj Optional instance to populate.
   * @return {module:model/InlineResponse40010} The populated <code>InlineResponse40010</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('submitTimeUtc')) {
        obj['submitTimeUtc'] = ApiClient.convertToType(data['submitTimeUtc'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], [PushFunds400ResponseDetails]);
      }
    }
    return obj;
  }

  /**
   * Request ID generated by Cybersource. This was sent in the header on the request. Echo value from x-requestid 
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`  **Example** `2023-05-17T22:47:57Z` equals May 17, 2023, at 22:47:57 (10:47:57 PM). The `T` separates the date and the time. The `Z` indicates UTC. 
   * @member {String} submitTimeUtc
   */
  exports.prototype['submitTimeUtc'] = undefined;
  /**
   * Message describing the status of the currency conversion request.   Possible values: - INVALID_REQUEST
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * The reason of the status.   Possible values: - MISSING_FIELD - INVALID_DATA
   * @member {String} reason
   */
  exports.prototype['reason'] = undefined;
  /**
   * Descriptive message to add more detail to the status 
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {Array.<module:model/PushFunds400ResponseDetails>} details
   */
  exports.prototype['details'] = undefined;



  return exports;
}));


