/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20011ResponseRecordAdditionalUpdates'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20011ResponseRecordAdditionalUpdates'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.InlineResponse20011ResponseRecord = factory(root.CyberSource.ApiClient, root.CyberSource.InlineResponse20011ResponseRecordAdditionalUpdates);
  }
}(this, function(ApiClient, InlineResponse20011ResponseRecordAdditionalUpdates) {
  'use strict';




  /**
   * The InlineResponse20011ResponseRecord model module.
   * @module model/InlineResponse20011ResponseRecord
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse20011ResponseRecord</code>.
   * @alias module:model/InlineResponse20011ResponseRecord
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>InlineResponse20011ResponseRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011ResponseRecord} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011ResponseRecord} The populated <code>InlineResponse20011ResponseRecord</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('response')) {
        obj['response'] = ApiClient.convertToType(data['response'], 'String');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
      if (data.hasOwnProperty('instrumentIdentifierId')) {
        obj['instrumentIdentifierId'] = ApiClient.convertToType(data['instrumentIdentifierId'], 'String');
      }
      if (data.hasOwnProperty('instrumentIdentifierCreated')) {
        obj['instrumentIdentifierCreated'] = ApiClient.convertToType(data['instrumentIdentifierCreated'], 'String');
      }
      if (data.hasOwnProperty('cardNumber')) {
        obj['cardNumber'] = ApiClient.convertToType(data['cardNumber'], 'String');
      }
      if (data.hasOwnProperty('cardExpiryMonth')) {
        obj['cardExpiryMonth'] = ApiClient.convertToType(data['cardExpiryMonth'], 'String');
      }
      if (data.hasOwnProperty('cardExpiryYear')) {
        obj['cardExpiryYear'] = ApiClient.convertToType(data['cardExpiryYear'], 'String');
      }
      if (data.hasOwnProperty('cardType')) {
        obj['cardType'] = ApiClient.convertToType(data['cardType'], 'String');
      }
      if (data.hasOwnProperty('additionalUpdates')) {
        obj['additionalUpdates'] = ApiClient.convertToType(data['additionalUpdates'], [InlineResponse20011ResponseRecordAdditionalUpdates]);
      }
    }
    return obj;
  }

  /**
   * Valid Values:   * NAN   * NED   * ACL   * CCH   * CUR   * NUP   * UNA   * ERR   * DEC 
   * @member {String} response
   */
  exports.prototype['response'] = undefined;
  /**
   * @member {String} reason
   */
  exports.prototype['reason'] = undefined;
  /**
   * @member {String} token
   */
  exports.prototype['token'] = undefined;
  /**
   * @member {String} instrumentIdentifierId
   */
  exports.prototype['instrumentIdentifierId'] = undefined;
  /**
   * Valid Values:   * true   * false 
   * @member {String} instrumentIdentifierCreated
   */
  exports.prototype['instrumentIdentifierCreated'] = undefined;
  /**
   * @member {String} cardNumber
   */
  exports.prototype['cardNumber'] = undefined;
  /**
   * @member {String} cardExpiryMonth
   */
  exports.prototype['cardExpiryMonth'] = undefined;
  /**
   * @member {String} cardExpiryYear
   */
  exports.prototype['cardExpiryYear'] = undefined;
  /**
   * @member {String} cardType
   */
  exports.prototype['cardType'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20011ResponseRecordAdditionalUpdates>} additionalUpdates
   */
  exports.prototype['additionalUpdates'] = undefined;



  return exports;
}));


