/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InvoicingV2InvoicesPost201ResponseOrderInformationAmountDetails', 'model/Invoicingv2invoicesOrderInformationLineItems'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InvoicingV2InvoicesPost201ResponseOrderInformationAmountDetails'), require('./Invoicingv2invoicesOrderInformationLineItems'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.InvoicingV2InvoicesPost201ResponseOrderInformation = factory(root.CyberSource.ApiClient, root.CyberSource.InvoicingV2InvoicesPost201ResponseOrderInformationAmountDetails, root.CyberSource.Invoicingv2invoicesOrderInformationLineItems);
  }
}(this, function(ApiClient, InvoicingV2InvoicesPost201ResponseOrderInformationAmountDetails, Invoicingv2invoicesOrderInformationLineItems) {
  'use strict';




  /**
   * The InvoicingV2InvoicesPost201ResponseOrderInformation model module.
   * @module model/InvoicingV2InvoicesPost201ResponseOrderInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InvoicingV2InvoicesPost201ResponseOrderInformation</code>.
   * Contains all of the order-related fields for the invoice.
   * @alias module:model/InvoicingV2InvoicesPost201ResponseOrderInformation
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InvoicingV2InvoicesPost201ResponseOrderInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvoicingV2InvoicesPost201ResponseOrderInformation} obj Optional instance to populate.
   * @return {module:model/InvoicingV2InvoicesPost201ResponseOrderInformation} The populated <code>InvoicingV2InvoicesPost201ResponseOrderInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amountDetails')) {
        obj['amountDetails'] = InvoicingV2InvoicesPost201ResponseOrderInformationAmountDetails.constructFromObject(data['amountDetails']);
      }
      if (data.hasOwnProperty('lineItems')) {
        obj['lineItems'] = ApiClient.convertToType(data['lineItems'], [Invoicingv2invoicesOrderInformationLineItems]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InvoicingV2InvoicesPost201ResponseOrderInformationAmountDetails} amountDetails
   */
  exports.prototype['amountDetails'] = undefined;
  /**
   * @member {Array.<module:model/Invoicingv2invoicesOrderInformationLineItems>} lineItems
   */
  exports.prototype['lineItems'] = undefined;



  return exports;
}));


