/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaymentInstrumentList1EmbeddedPaymentInstruments'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaymentInstrumentList1EmbeddedPaymentInstruments'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.PaymentInstrumentList1Embedded = factory(root.CyberSource.ApiClient, root.CyberSource.PaymentInstrumentList1EmbeddedPaymentInstruments);
  }
}(this, function(ApiClient, PaymentInstrumentList1EmbeddedPaymentInstruments) {
  'use strict';




  /**
   * The PaymentInstrumentList1Embedded model module.
   * @module model/PaymentInstrumentList1Embedded
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>PaymentInstrumentList1Embedded</code>.
   * Payment Instrument Resources. 
   * @alias module:model/PaymentInstrumentList1Embedded
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PaymentInstrumentList1Embedded</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentInstrumentList1Embedded} obj Optional instance to populate.
   * @return {module:model/PaymentInstrumentList1Embedded} The populated <code>PaymentInstrumentList1Embedded</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('paymentInstruments')) {
        obj['paymentInstruments'] = ApiClient.convertToType(data['paymentInstruments'], [PaymentInstrumentList1EmbeddedPaymentInstruments]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PaymentInstrumentList1EmbeddedPaymentInstruments>} paymentInstruments
   */
  exports.prototype['paymentInstruments'] = undefined;



  return exports;
}));


