/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TmsMerchantInformation', 'model/Tmsv3tokenstokenIdpaymentcredentialsAuthenticatedIdentities', 'model/Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation', 'model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TmsMerchantInformation'), require('./Tmsv3tokenstokenIdpaymentcredentialsAuthenticatedIdentities'), require('./Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation'), require('./Tmsv3tokenstokenIdpaymentcredentialsOrderInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.PostPaymentCredentialsRequest1 = factory(root.CyberSource.ApiClient, root.CyberSource.TmsMerchantInformation, root.CyberSource.Tmsv3tokenstokenIdpaymentcredentialsAuthenticatedIdentities, root.CyberSource.Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation, root.CyberSource.Tmsv3tokenstokenIdpaymentcredentialsOrderInformation);
  }
}(this, function(ApiClient, TmsMerchantInformation, Tmsv3tokenstokenIdpaymentcredentialsAuthenticatedIdentities, Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation, Tmsv3tokenstokenIdpaymentcredentialsOrderInformation) {
  'use strict';




  /**
   * The PostPaymentCredentialsRequest1 model module.
   * @module model/PostPaymentCredentialsRequest1
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>PostPaymentCredentialsRequest1</code>.
   * @alias module:model/PostPaymentCredentialsRequest1
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PostPaymentCredentialsRequest1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostPaymentCredentialsRequest1} obj Optional instance to populate.
   * @return {module:model/PostPaymentCredentialsRequest1} The populated <code>PostPaymentCredentialsRequest1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('paymentCredentialType')) {
        obj['paymentCredentialType'] = ApiClient.convertToType(data['paymentCredentialType'], 'String');
      }
      if (data.hasOwnProperty('transactionType')) {
        obj['transactionType'] = ApiClient.convertToType(data['transactionType'], 'String');
      }
      if (data.hasOwnProperty('clientCorrelationId')) {
        obj['clientCorrelationId'] = ApiClient.convertToType(data['clientCorrelationId'], 'String');
      }
      if (data.hasOwnProperty('orderInformation')) {
        obj['orderInformation'] = Tmsv3tokenstokenIdpaymentcredentialsOrderInformation.constructFromObject(data['orderInformation']);
      }
      if (data.hasOwnProperty('merchantInformation')) {
        obj['merchantInformation'] = TmsMerchantInformation.constructFromObject(data['merchantInformation']);
      }
      if (data.hasOwnProperty('deviceInformation')) {
        obj['deviceInformation'] = Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation.constructFromObject(data['deviceInformation']);
      }
      if (data.hasOwnProperty('authenticatedIdentities')) {
        obj['authenticatedIdentities'] = ApiClient.convertToType(data['authenticatedIdentities'], [Tmsv3tokenstokenIdpaymentcredentialsAuthenticatedIdentities]);
      }
    }
    return obj;
  }

  /**
   * The type of payment credentials to be returned. By default, payment credentials include network token and cryptogram or dynamic CVV. If \"NETWORK_TOKEN\" is supplied then only network token card number will be returned and no cryptogram or dynamic CVV will be requested. If \"SECURITY_CODE\" is supplied then dynamic CVV will be requested and returned with the network token card number. Dynamic CVV is only supported for Amex and SCOF. If \"CRYPTOGRAM\" is supplied then cryptogram will be requested and returned with the network token card number. Cryptogram is NOT supported for Amex.  Possible Values:   - NETWORK_TOKEN   - SECURITY_CODE   - CRYPTOGRAM 
   * @member {String} paymentCredentialType
   */
  exports.prototype['paymentCredentialType'] = undefined;
  /**
   * Specifies the type of transaction for which the network token credentials are required. Possible Values:   - ECOM: Ecommerce transaction. If transactionType is not provided, ECOM is set as the default.   - AFT: Account Funding Transaction. This is only supported for VISA and paymentCredentialType of CRYPTOGRAM. 
   * @member {String} transactionType
   */
  exports.prototype['transactionType'] = undefined;
  /**
   * Used to correlate authentication and payment credential requests. 
   * @member {String} clientCorrelationId
   */
  exports.prototype['clientCorrelationId'] = undefined;
  /**
   * @member {module:model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformation} orderInformation
   */
  exports.prototype['orderInformation'] = undefined;
  /**
   * @member {module:model/TmsMerchantInformation} merchantInformation
   */
  exports.prototype['merchantInformation'] = undefined;
  /**
   * @member {module:model/Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation} deviceInformation
   */
  exports.prototype['deviceInformation'] = undefined;
  /**
   * @member {Array.<module:model/Tmsv3tokenstokenIdpaymentcredentialsAuthenticatedIdentities>} authenticatedIdentities
   */
  exports.prototype['authenticatedIdentities'] = undefined;



  return exports;
}));


