/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Ptsv2intentsRecipientInformation = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ptsv2intentsRecipientInformation model module.
   * @module model/Ptsv2intentsRecipientInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Ptsv2intentsRecipientInformation</code>.
   * @alias module:model/Ptsv2intentsRecipientInformation
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Ptsv2intentsRecipientInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ptsv2intentsRecipientInformation} obj Optional instance to populate.
   * @return {module:model/Ptsv2intentsRecipientInformation} The populated <code>Ptsv2intentsRecipientInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
      }
      if (data.hasOwnProperty('createDate')) {
        obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('countryCode')) {
        obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
      }
      if (data.hasOwnProperty('businessName')) {
        obj['businessName'] = ApiClient.convertToType(data['businessName'], 'String');
      }
      if (data.hasOwnProperty('riskPopularityScore')) {
        obj['riskPopularityScore'] = ApiClient.convertToType(data['riskPopularityScore'], 'String');
      }
    }
    return obj;
  }

  /**
   * The account ID of the recipient. 
   * @member {String} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * The date when the recipient's account was created. 
   * @member {String} createDate
   */
  exports.prototype['createDate'] = undefined;
  /**
   * The email address of the recipient 
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * The country code of the recipient. 
   * @member {String} countryCode
   */
  exports.prototype['countryCode'] = undefined;
  /**
   * The business name of the recipient. 
   * @member {String} businessName
   */
  exports.prototype['businessName'] = undefined;
  /**
   * The risk popularity score of the recipient. 
   * @member {String} riskPopularityScore
   */
  exports.prototype['riskPopularityScore'] = undefined;



  return exports;
}));


