/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PullFunds201ResponseProcessorInformationAvs', 'model/PullFunds201ResponseProcessorInformationConsumerAuthenticationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PullFunds201ResponseProcessorInformationAvs'), require('./PullFunds201ResponseProcessorInformationConsumerAuthenticationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.PullFunds201ResponseProcessorInformation = factory(root.CyberSource.ApiClient, root.CyberSource.PullFunds201ResponseProcessorInformationAvs, root.CyberSource.PullFunds201ResponseProcessorInformationConsumerAuthenticationResponse);
  }
}(this, function(ApiClient, PullFunds201ResponseProcessorInformationAvs, PullFunds201ResponseProcessorInformationConsumerAuthenticationResponse) {
  'use strict';




  /**
   * The PullFunds201ResponseProcessorInformation model module.
   * @module model/PullFunds201ResponseProcessorInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>PullFunds201ResponseProcessorInformation</code>.
   * @alias module:model/PullFunds201ResponseProcessorInformation
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PullFunds201ResponseProcessorInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PullFunds201ResponseProcessorInformation} obj Optional instance to populate.
   * @return {module:model/PullFunds201ResponseProcessorInformation} The populated <code>PullFunds201ResponseProcessorInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('systemTraceAuditNumber')) {
        obj['systemTraceAuditNumber'] = ApiClient.convertToType(data['systemTraceAuditNumber'], 'String');
      }
      if (data.hasOwnProperty('approvalCode')) {
        obj['approvalCode'] = ApiClient.convertToType(data['approvalCode'], 'String');
      }
      if (data.hasOwnProperty('responseCode')) {
        obj['responseCode'] = ApiClient.convertToType(data['responseCode'], 'String');
      }
      if (data.hasOwnProperty('transactionId')) {
        obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
      }
      if (data.hasOwnProperty('consumerAuthenticationResponse')) {
        obj['consumerAuthenticationResponse'] = PullFunds201ResponseProcessorInformationConsumerAuthenticationResponse.constructFromObject(data['consumerAuthenticationResponse']);
      }
      if (data.hasOwnProperty('retrievalReferenceNumber')) {
        obj['retrievalReferenceNumber'] = ApiClient.convertToType(data['retrievalReferenceNumber'], 'String');
      }
      if (data.hasOwnProperty('avs')) {
        obj['avs'] = PullFunds201ResponseProcessorInformationAvs.constructFromObject(data['avs']);
      }
      if (data.hasOwnProperty('responseDetails')) {
        obj['responseDetails'] = ApiClient.convertToType(data['responseDetails'], 'String');
      }
    }
    return obj;
  }

  /**
   * This field is returned by authorization and incremental authorization services. System trace number that must be printed on the customer's receipt. 
   * @member {String} systemTraceAuditNumber
   */
  exports.prototype['systemTraceAuditNumber'] = undefined;
  /**
   * Issuer-generated approval code for the transaction. 
   * @member {String} approvalCode
   */
  exports.prototype['approvalCode'] = undefined;
  /**
   * Transaction status from the processor. 
   * @member {String} responseCode
   */
  exports.prototype['responseCode'] = undefined;
  /**
   * Network transaction identifier (TID). This value can be used to identify a specific transaction when you are discussing the transaction with your processor. 
   * @member {String} transactionId
   */
  exports.prototype['transactionId'] = undefined;
  /**
   * @member {module:model/PullFunds201ResponseProcessorInformationConsumerAuthenticationResponse} consumerAuthenticationResponse
   */
  exports.prototype['consumerAuthenticationResponse'] = undefined;
  /**
   * This field contains a number that is used with other data elements as a key to identify and track all messages related to a given cardholder transaction; that is, to a given transaction set.  Recommended format: ydddhhnnnnnn   Positions 1-4: The yddd equivalent of the date, where y = 0-9 and ddd = 001 – 366.  Positions 5-12: A unique identification number generated by the merchant or assigned by Cybersource. 
   * @member {String} retrievalReferenceNumber
   */
  exports.prototype['retrievalReferenceNumber'] = undefined;
  /**
   * @member {module:model/PullFunds201ResponseProcessorInformationAvs} avs
   */
  exports.prototype['avs'] = undefined;
  /**
   * This field might contain information about a decline. 
   * @member {String} responseDetails
   */
  exports.prototype['responseDetails'] = undefined;



  return exports;
}));


