/**
 * CyberSource Flex API
 * Simple PAN tokenization service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ReportingV3ReportsGet200ResponseReports'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ReportingV3ReportsGet200ResponseReports'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.ReportingV3ReportsGet200Response = factory(root.CyberSource.ApiClient, root.CyberSource.ReportingV3ReportsGet200ResponseReports);
  }
}(this, function(ApiClient, ReportingV3ReportsGet200ResponseReports) {
  'use strict';




  /**
   * The ReportingV3ReportsGet200Response model module.
   * @module model/ReportingV3ReportsGet200Response
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ReportingV3ReportsGet200Response</code>.
   * @alias module:model/ReportingV3ReportsGet200Response
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ReportingV3ReportsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportingV3ReportsGet200Response} obj Optional instance to populate.
   * @return {module:model/ReportingV3ReportsGet200Response} The populated <code>ReportingV3ReportsGet200Response</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('reports')) {
        obj['reports'] = ApiClient.convertToType(data['reports'], [ReportingV3ReportsGet200ResponseReports]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ReportingV3ReportsGet200ResponseReports>} reports
   */
  exports.prototype['reports'] = undefined;



  return exports;
}));


