/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.RiskV1DecisionsPost201ResponseRiskInformationProfile = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RiskV1DecisionsPost201ResponseRiskInformationProfile model module.
   * @module model/RiskV1DecisionsPost201ResponseRiskInformationProfile
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>RiskV1DecisionsPost201ResponseRiskInformationProfile</code>.
   * @alias module:model/RiskV1DecisionsPost201ResponseRiskInformationProfile
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>RiskV1DecisionsPost201ResponseRiskInformationProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RiskV1DecisionsPost201ResponseRiskInformationProfile} obj Optional instance to populate.
   * @return {module:model/RiskV1DecisionsPost201ResponseRiskInformationProfile} The populated <code>RiskV1DecisionsPost201ResponseRiskInformationProfile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('desinationQueue')) {
        obj['desinationQueue'] = ApiClient.convertToType(data['desinationQueue'], 'String');
      }
      if (data.hasOwnProperty('selectorRule')) {
        obj['selectorRule'] = ApiClient.convertToType(data['selectorRule'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the active profile chosen by the profile selector. If no profile selector exists, the default active profile is chosen.  **Note** By default, your default profile is the active profile, or the Profile Selector chooses the active profile. Use this field only if you want to specify the name of a different profile. The passed-in profile will then become the active profile. 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Name of the queue where orders that are not automatically accepted are sent. 
   * @member {String} desinationQueue
   */
  exports.prototype['desinationQueue'] = undefined;
  /**
   * Name of the profile selector rule that chooses the profile to use for the transaction. If no profile selector exists, the value is Default Active Profile. 
   * @member {String} selectorRule
   */
  exports.prototype['selectorRule'] = undefined;



  return exports;
}));


