/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchListMatches'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchListMatches'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList = factory(root.CyberSource.ApiClient, root.CyberSource.RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchListMatches);
  }
}(this, function(ApiClient, RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchListMatches) {
  'use strict';




  /**
   * The RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList model module.
   * @module model/RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList</code>.
   * @alias module:model/RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList} obj Optional instance to populate.
   * @return {module:model/RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList} The populated <code>RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('matches')) {
        obj['matches'] = ApiClient.convertToType(data['matches'], [RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchListMatches]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchListMatches>} matches
   */
  exports.prototype['matches'] = undefined;



  return exports;
}));


