/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilinkCredentials'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilinkCredentials'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink = factory(root.CyberSource.ApiClient, root.CyberSource.RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilinkCredentials);
  }
}(this, function(ApiClient, RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilinkCredentials) {
  'use strict';




  /**
   * The RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink model module.
   * @module model/RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink</code>.
   * @alias module:model/RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink} obj Optional instance to populate.
   * @return {module:model/RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink} The populated <code>RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilink</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('enabled')) {
        obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
      }
      if (data.hasOwnProperty('enableRealTime')) {
        obj['enableRealTime'] = ApiClient.convertToType(data['enableRealTime'], 'Boolean');
      }
      if (data.hasOwnProperty('useCybsCredentials')) {
        obj['useCybsCredentials'] = ApiClient.convertToType(data['useCybsCredentials'], 'Boolean');
      }
      if (data.hasOwnProperty('credentials')) {
        obj['credentials'] = RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilinkCredentials.constructFromObject(data['credentials']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} enabled
   */
  exports.prototype['enabled'] = undefined;
  /**
   * @member {Boolean} enableRealTime
   */
  exports.prototype['enableRealTime'] = undefined;
  /**
   * @member {Boolean} useCybsCredentials
   */
  exports.prototype['useCybsCredentials'] = undefined;
  /**
   * @member {module:model/RiskProductsDecisionManagerConfigurationInformationConfigurationsThirdpartyProviderCredilinkCredentials} credentials
   */
  exports.prototype['credentials'] = undefined;



  return exports;
}));


