/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TmsEmbeddedInstrumentIdentifierLinksPaymentInstruments', 'model/TmsEmbeddedInstrumentIdentifierLinksSelf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TmsEmbeddedInstrumentIdentifierLinksPaymentInstruments'), require('./TmsEmbeddedInstrumentIdentifierLinksSelf'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.TmsEmbeddedInstrumentIdentifierLinks = factory(root.CyberSource.ApiClient, root.CyberSource.TmsEmbeddedInstrumentIdentifierLinksPaymentInstruments, root.CyberSource.TmsEmbeddedInstrumentIdentifierLinksSelf);
  }
}(this, function(ApiClient, TmsEmbeddedInstrumentIdentifierLinksPaymentInstruments, TmsEmbeddedInstrumentIdentifierLinksSelf) {
  'use strict';




  /**
   * The TmsEmbeddedInstrumentIdentifierLinks model module.
   * @module model/TmsEmbeddedInstrumentIdentifierLinks
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>TmsEmbeddedInstrumentIdentifierLinks</code>.
   * @alias module:model/TmsEmbeddedInstrumentIdentifierLinks
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TmsEmbeddedInstrumentIdentifierLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TmsEmbeddedInstrumentIdentifierLinks} obj Optional instance to populate.
   * @return {module:model/TmsEmbeddedInstrumentIdentifierLinks} The populated <code>TmsEmbeddedInstrumentIdentifierLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('self')) {
        obj['self'] = TmsEmbeddedInstrumentIdentifierLinksSelf.constructFromObject(data['self']);
      }
      if (data.hasOwnProperty('paymentInstruments')) {
        obj['paymentInstruments'] = TmsEmbeddedInstrumentIdentifierLinksPaymentInstruments.constructFromObject(data['paymentInstruments']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/TmsEmbeddedInstrumentIdentifierLinksSelf} self
   */
  exports.prototype['self'] = undefined;
  /**
   * @member {module:model/TmsEmbeddedInstrumentIdentifierLinksPaymentInstruments} paymentInstruments
   */
  exports.prototype['paymentInstruments'] = undefined;



  return exports;
}));


