/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TmsPointOfSaleInformationEmvTags'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TmsPointOfSaleInformationEmvTags'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.TmsPointOfSaleInformation = factory(root.CyberSource.ApiClient, root.CyberSource.TmsPointOfSaleInformationEmvTags);
  }
}(this, function(ApiClient, TmsPointOfSaleInformationEmvTags) {
  'use strict';




  /**
   * The TmsPointOfSaleInformation model module.
   * @module model/TmsPointOfSaleInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>TmsPointOfSaleInformation</code>.
   * @alias module:model/TmsPointOfSaleInformation
   * @class
   * @param emvTags {Array.<module:model/TmsPointOfSaleInformationEmvTags>} 
   */
  var exports = function(emvTags) {
    var _this = this;

    _this['emvTags'] = emvTags;
  };

  /**
   * Constructs a <code>TmsPointOfSaleInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TmsPointOfSaleInformation} obj Optional instance to populate.
   * @return {module:model/TmsPointOfSaleInformation} The populated <code>TmsPointOfSaleInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('emvTags')) {
        obj['emvTags'] = ApiClient.convertToType(data['emvTags'], [TmsPointOfSaleInformationEmvTags]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/TmsPointOfSaleInformationEmvTags>} emvTags
   */
  exports.prototype['emvTags'] = undefined;



  return exports;
}));


