/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinksSelf', 'model/Tmsv2tokenizeTokenInformationCustomerLinksSelf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinksSelf'), require('./Tmsv2tokenizeTokenInformationCustomerLinksSelf'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks = factory(root.CyberSource.ApiClient, root.CyberSource.Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinksSelf, root.CyberSource.Tmsv2tokenizeTokenInformationCustomerLinksSelf);
  }
}(this, function(ApiClient, Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinksSelf, Tmsv2tokenizeTokenInformationCustomerLinksSelf) {
  'use strict';




  /**
   * The Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks model module.
   * @module model/Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks</code>.
   * @alias module:model/Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks} obj Optional instance to populate.
   * @return {module:model/Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks} The populated <code>Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('self')) {
        obj['self'] = Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinksSelf.constructFromObject(data['self']);
      }
      if (data.hasOwnProperty('customer')) {
        obj['customer'] = Tmsv2tokenizeTokenInformationCustomerLinksSelf.constructFromObject(data['customer']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Tmsv2tokenizeTokenInformationCustomerEmbeddedDefaultPaymentInstrumentLinksSelf} self
   */
  exports.prototype['self'] = undefined;
  /**
   * @member {module:model/Tmsv2tokenizeTokenInformationCustomerLinksSelf} customer
   */
  exports.prototype['customer'] = undefined;



  return exports;
}));


