/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset model module.
   * @module model/Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset</code>.
   * @alias module:model/Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset} obj Optional instance to populate.
   * @return {module:model/Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset} The populated <code>Tmsv2tokenizedcardstokenizedCardIdissuerlifecycleeventsimulationsMetadataCardArtCombinedAsset</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('update')) {
        obj['update'] = ApiClient.convertToType(data['update'], 'String');
      }
    }
    return obj;
  }

  /**
   * Set to \"true\" to simulate an update to the combined card art asset associated with the Tokenized Card. 
   * @member {String} update
   */
  exports.prototype['update'] = undefined;



  return exports;
}));


