/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Tmsv2tokenizedcardsBillTo', 'model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformationAmountDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Tmsv2tokenizedcardsBillTo'), require('./Tmsv3tokenstokenIdpaymentcredentialsOrderInformationAmountDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Tmsv3tokenstokenIdpaymentcredentialsOrderInformation = factory(root.CyberSource.ApiClient, root.CyberSource.Tmsv2tokenizedcardsBillTo, root.CyberSource.Tmsv3tokenstokenIdpaymentcredentialsOrderInformationAmountDetails);
  }
}(this, function(ApiClient, Tmsv2tokenizedcardsBillTo, Tmsv3tokenstokenIdpaymentcredentialsOrderInformationAmountDetails) {
  'use strict';




  /**
   * The Tmsv3tokenstokenIdpaymentcredentialsOrderInformation model module.
   * @module model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Tmsv3tokenstokenIdpaymentcredentialsOrderInformation</code>.
   * @alias module:model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformation
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Tmsv3tokenstokenIdpaymentcredentialsOrderInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformation} obj Optional instance to populate.
   * @return {module:model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformation} The populated <code>Tmsv3tokenstokenIdpaymentcredentialsOrderInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amountDetails')) {
        obj['amountDetails'] = Tmsv3tokenstokenIdpaymentcredentialsOrderInformationAmountDetails.constructFromObject(data['amountDetails']);
      }
      if (data.hasOwnProperty('billTo')) {
        obj['billTo'] = Tmsv2tokenizedcardsBillTo.constructFromObject(data['billTo']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Tmsv3tokenstokenIdpaymentcredentialsOrderInformationAmountDetails} amountDetails
   */
  exports.prototype['amountDetails'] = undefined;
  /**
   * @member {module:model/Tmsv2tokenizedcardsBillTo} billTo
   */
  exports.prototype['billTo'] = undefined;



  return exports;
}));


