/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource model module.
   * @module model/TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource</code>.
   * @alias module:model/TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource} obj Optional instance to populate.
   * @return {module:model/TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource} The populated <code>TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeFundingSource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('credential')) {
        obj['credential'] = ApiClient.convertToType(data['credential'], 'String');
      }
      if (data.hasOwnProperty('affiliations')) {
        obj['affiliations'] = ApiClient.convertToType(data['affiliations'], 'String');
      }
      if (data.hasOwnProperty('underwriter')) {
        obj['underwriter'] = ApiClient.convertToType(data['underwriter'], 'String');
      }
    }
    return obj;
  }

  /**
   * A Payment Type Funding Source is the Financial Account which holds the financial assets used to fund a transaction initiated with a given Payment Type. Examples: Bank of America Debit, Wells Consumer Checking 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * It is type of funding source. Examples: US Checking Account, Credit Account, Stored Value Account 
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * It is the credential of the funding source. Examples: Credit Card PAN, Checking Account Number 
   * @member {String} credential
   */
  exports.prototype['credential'] = undefined;
  /**
   * It is affiliation of funding source such as Visa, Master Card, ACH. 
   * @member {String} affiliations
   */
  exports.prototype['affiliations'] = undefined;
  /**
   * It is underwrite for the given funding source. Examples: Bank of America, Wells Fargo, PayPal 
   * @member {String} underwriter
   */
  exports.prototype['underwriter'] = undefined;



  return exports;
}));


