/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Ucv1sessionsDataConsumerAuthenticationInformation = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ucv1sessionsDataConsumerAuthenticationInformation model module.
   * @module model/Ucv1sessionsDataConsumerAuthenticationInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Ucv1sessionsDataConsumerAuthenticationInformation</code>.
   * @alias module:model/Ucv1sessionsDataConsumerAuthenticationInformation
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Ucv1sessionsDataConsumerAuthenticationInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ucv1sessionsDataConsumerAuthenticationInformation} obj Optional instance to populate.
   * @return {module:model/Ucv1sessionsDataConsumerAuthenticationInformation} The populated <code>Ucv1sessionsDataConsumerAuthenticationInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('challengeCode')) {
        obj['challengeCode'] = ApiClient.convertToType(data['challengeCode'], 'String');
      }
      if (data.hasOwnProperty('messageCategory')) {
        obj['messageCategory'] = ApiClient.convertToType(data['messageCategory'], 'String');
      }
      if (data.hasOwnProperty('acsWindowSize')) {
        obj['acsWindowSize'] = ApiClient.convertToType(data['acsWindowSize'], 'String');
      }
      if (data.hasOwnProperty('productCode')) {
        obj['productCode'] = ApiClient.convertToType(data['productCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * The challenge code<br><br>  Optional field: This field cannot be configured through the Merchant Experience screens in the Business Center, but if required should be provided on a per‑transaction basis in the uc/v1/sessions API request. 
   * @member {String} challengeCode
   */
  exports.prototype['challengeCode'] = undefined;
  /**
   * The message category<br><br>  Optional field: This field cannot be configured through the Merchant Experience screens in the Business Center, but if required should be provided on a per‑transaction basis in the uc/v1/sessions API request. 
   * @member {String} messageCategory
   */
  exports.prototype['messageCategory'] = undefined;
  /**
   * The acs window size<br><br>  Optional field: This field cannot be configured through the Merchant Experience screens in the Business Center, but if required should be provided on a per‑transaction basis in the uc/v1/sessions API request. 
   * @member {String} acsWindowSize
   */
  exports.prototype['acsWindowSize'] = undefined;
  /**
   * Specifies the product code, which designates the type of transaction.<br><br>  Specify one of the following values for this field:  - AIR: Airline purchase  Important Required for American Express SafeKey (U.S.).  - ACC: Accommodation Rental  - ACF: Account funding  - CHA: Check acceptance  - DIG: Digital Goods  - DSP: Cash Dispensing  - GAS: Fuel  - GEN: General Retail  - LUX: Luxury Retail  - PAL: Prepaid activation and load  - PHY: Goods or services purchase  - QCT: Quasi-cash transaction  - REN: Car Rental  - RES: Restaurant  - SVC: Services  - TBD: Other  - TRA: Travel<br>  **Important** Required for Visa Secure transactions in Brazil. Do not use this request field for any other types of transactions. 
   * @member {String} productCode
   */
  exports.prototype['productCode'] = undefined;



  return exports;
}));


