/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Ucv1sessionsCompleteMandateTms = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ucv1sessionsCompleteMandateTms model module.
   * @module model/Ucv1sessionsCompleteMandateTms
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Ucv1sessionsCompleteMandateTms</code>.
   * Configure Unified Checkout to create a TMS token at the end of the payment journey 
   * @alias module:model/Ucv1sessionsCompleteMandateTms
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Ucv1sessionsCompleteMandateTms</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ucv1sessionsCompleteMandateTms} obj Optional instance to populate.
   * @return {module:model/Ucv1sessionsCompleteMandateTms} The populated <code>Ucv1sessionsCompleteMandateTms</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tokenCreate')) {
        obj['tokenCreate'] = ApiClient.convertToType(data['tokenCreate'], 'Boolean');
      }
      if (data.hasOwnProperty('tokenTypes')) {
        obj['tokenTypes'] = ApiClient.convertToType(data['tokenTypes'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Use this when you want to create a token from the card/bank data in your payment request.   Possible values:   - True   - False<br><br>  Optional field: This field can be configured through the Merchant Experience screens in the Business Center. The configured value may be overridden on a per‑transaction basis in the uc/v1/sessions API request. 
   * @member {Boolean} tokenCreate
   */
  exports.prototype['tokenCreate'] = undefined;
  /**
   * Cybersource tokens types you are performing a create on. If not supplied the default token type for the merchants token vault will be used.  Possible values: - Customer - paymentInstrument - instrumentIdentifier - shippingAddress<br><br>  Optional field: This field can be configured through the Merchant Experience screens in the Business Center. The configured value may be overridden on a per‑transaction basis in the uc/v1/sessions API request. 
   * @member {Array.<String>} tokenTypes
   */
  exports.prototype['tokenTypes'] = undefined;



  return exports;
}));


