/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Ucv1sessionsDataBuyerInformation', 'model/Ucv1sessionsDataConsumerAuthenticationInformation', 'model/Ucv1sessionsDataDeviceInformation', 'model/Ucv1sessionsDataMerchantDefinedInformation', 'model/Ucv1sessionsDataMerchantInformation', 'model/Ucv1sessionsDataOrderInformation', 'model/Ucv1sessionsDataPaymentInformation', 'model/Ucv1sessionsDataProcessingInformation', 'model/Ucv1sessionsDataRecipientInformation', 'model/Upv1capturecontextsDataClientReferenceInformation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Ucv1sessionsDataBuyerInformation'), require('./Ucv1sessionsDataConsumerAuthenticationInformation'), require('./Ucv1sessionsDataDeviceInformation'), require('./Ucv1sessionsDataMerchantDefinedInformation'), require('./Ucv1sessionsDataMerchantInformation'), require('./Ucv1sessionsDataOrderInformation'), require('./Ucv1sessionsDataPaymentInformation'), require('./Ucv1sessionsDataProcessingInformation'), require('./Ucv1sessionsDataRecipientInformation'), require('./Upv1capturecontextsDataClientReferenceInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.Ucv1sessionsData = factory(root.CyberSource.ApiClient, root.CyberSource.Ucv1sessionsDataBuyerInformation, root.CyberSource.Ucv1sessionsDataConsumerAuthenticationInformation, root.CyberSource.Ucv1sessionsDataDeviceInformation, root.CyberSource.Ucv1sessionsDataMerchantDefinedInformation, root.CyberSource.Ucv1sessionsDataMerchantInformation, root.CyberSource.Ucv1sessionsDataOrderInformation, root.CyberSource.Ucv1sessionsDataPaymentInformation, root.CyberSource.Ucv1sessionsDataProcessingInformation, root.CyberSource.Ucv1sessionsDataRecipientInformation, root.CyberSource.Upv1capturecontextsDataClientReferenceInformation);
  }
}(this, function(ApiClient, Ucv1sessionsDataBuyerInformation, Ucv1sessionsDataConsumerAuthenticationInformation, Ucv1sessionsDataDeviceInformation, Ucv1sessionsDataMerchantDefinedInformation, Ucv1sessionsDataMerchantInformation, Ucv1sessionsDataOrderInformation, Ucv1sessionsDataPaymentInformation, Ucv1sessionsDataProcessingInformation, Ucv1sessionsDataRecipientInformation, Upv1capturecontextsDataClientReferenceInformation) {
  'use strict';




  /**
   * The Ucv1sessionsData model module.
   * @module model/Ucv1sessionsData
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Ucv1sessionsData</code>.
   * @alias module:model/Ucv1sessionsData
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>Ucv1sessionsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ucv1sessionsData} obj Optional instance to populate.
   * @return {module:model/Ucv1sessionsData} The populated <code>Ucv1sessionsData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderInformation')) {
        obj['orderInformation'] = Ucv1sessionsDataOrderInformation.constructFromObject(data['orderInformation']);
      }
      if (data.hasOwnProperty('buyerInformation')) {
        obj['buyerInformation'] = Ucv1sessionsDataBuyerInformation.constructFromObject(data['buyerInformation']);
      }
      if (data.hasOwnProperty('clientReferenceInformation')) {
        obj['clientReferenceInformation'] = Upv1capturecontextsDataClientReferenceInformation.constructFromObject(data['clientReferenceInformation']);
      }
      if (data.hasOwnProperty('consumerAuthenticationInformation')) {
        obj['consumerAuthenticationInformation'] = Ucv1sessionsDataConsumerAuthenticationInformation.constructFromObject(data['consumerAuthenticationInformation']);
      }
      if (data.hasOwnProperty('merchantInformation')) {
        obj['merchantInformation'] = Ucv1sessionsDataMerchantInformation.constructFromObject(data['merchantInformation']);
      }
      if (data.hasOwnProperty('processingInformation')) {
        obj['processingInformation'] = Ucv1sessionsDataProcessingInformation.constructFromObject(data['processingInformation']);
      }
      if (data.hasOwnProperty('recipientInformation')) {
        obj['recipientInformation'] = Ucv1sessionsDataRecipientInformation.constructFromObject(data['recipientInformation']);
      }
      if (data.hasOwnProperty('merchantDefinedInformation')) {
        obj['merchantDefinedInformation'] = ApiClient.convertToType(data['merchantDefinedInformation'], [Ucv1sessionsDataMerchantDefinedInformation]);
      }
      if (data.hasOwnProperty('deviceInformation')) {
        obj['deviceInformation'] = Ucv1sessionsDataDeviceInformation.constructFromObject(data['deviceInformation']);
      }
      if (data.hasOwnProperty('paymentInformation')) {
        obj['paymentInformation'] = Ucv1sessionsDataPaymentInformation.constructFromObject(data['paymentInformation']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Ucv1sessionsDataOrderInformation} orderInformation
   */
  exports.prototype['orderInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataBuyerInformation} buyerInformation
   */
  exports.prototype['buyerInformation'] = undefined;
  /**
   * @member {module:model/Upv1capturecontextsDataClientReferenceInformation} clientReferenceInformation
   */
  exports.prototype['clientReferenceInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataConsumerAuthenticationInformation} consumerAuthenticationInformation
   */
  exports.prototype['consumerAuthenticationInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataMerchantInformation} merchantInformation
   */
  exports.prototype['merchantInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataProcessingInformation} processingInformation
   */
  exports.prototype['processingInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataRecipientInformation} recipientInformation
   */
  exports.prototype['recipientInformation'] = undefined;
  /**
   * @member {Array.<module:model/Ucv1sessionsDataMerchantDefinedInformation>} merchantDefinedInformation
   */
  exports.prototype['merchantDefinedInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataDeviceInformation} deviceInformation
   */
  exports.prototype['deviceInformation'] = undefined;
  /**
   * @member {module:model/Ucv1sessionsDataPaymentInformation} paymentInformation
   */
  exports.prototype['paymentInformation'] = undefined;



  return exports;
}));


