/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UnderwritingConfigurationOrganizationInformationBusinessInformation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UnderwritingConfigurationOrganizationInformationBusinessInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.UnderwritingConfigurationOrganizationInformation = factory(root.CyberSource.ApiClient, root.CyberSource.UnderwritingConfigurationOrganizationInformationBusinessInformation);
  }
}(this, function(ApiClient, UnderwritingConfigurationOrganizationInformationBusinessInformation) {
  'use strict';




  /**
   * The UnderwritingConfigurationOrganizationInformation model module.
   * @module model/UnderwritingConfigurationOrganizationInformation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>UnderwritingConfigurationOrganizationInformation</code>.
   * @alias module:model/UnderwritingConfigurationOrganizationInformation
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>UnderwritingConfigurationOrganizationInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnderwritingConfigurationOrganizationInformation} obj Optional instance to populate.
   * @return {module:model/UnderwritingConfigurationOrganizationInformation} The populated <code>UnderwritingConfigurationOrganizationInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('parentOrganizationId')) {
        obj['parentOrganizationId'] = ApiClient.convertToType(data['parentOrganizationId'], 'String');
      }
      if (data.hasOwnProperty('organizationId')) {
        obj['organizationId'] = ApiClient.convertToType(data['organizationId'], 'String');
      }
      if (data.hasOwnProperty('boardingPackageId')) {
        obj['boardingPackageId'] = ApiClient.convertToType(data['boardingPackageId'], 'String');
      }
      if (data.hasOwnProperty('businessInformation')) {
        obj['businessInformation'] = UnderwritingConfigurationOrganizationInformationBusinessInformation.constructFromObject(data['businessInformation']);
      }
    }
    return obj;
  }

  /**
   * Parent Organization ID for the application
   * @member {String} parentOrganizationId
   */
  exports.prototype['parentOrganizationId'] = undefined;
  /**
   * Organization ID for the application
   * @member {String} organizationId
   */
  exports.prototype['organizationId'] = undefined;
  /**
   * Boarding Package ID for the application
   * @member {String} boardingPackageId
   */
  exports.prototype['boardingPackageId'] = undefined;
  /**
   * @member {module:model/UnderwritingConfigurationOrganizationInformationBusinessInformation} businessInformation
   */
  exports.prototype['businessInformation'] = undefined;



  return exports;
}));


