/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.UnifiedriskPaymentSdk = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UnifiedriskPaymentSdk model module.
   * @module model/UnifiedriskPaymentSdk
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>UnifiedriskPaymentSdk</code>.
   * Container for 3DS SDK authentication data, including device encryption keys, application identifiers, and authentication flow parameters
   * @alias module:model/UnifiedriskPaymentSdk
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>UnifiedriskPaymentSdk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnifiedriskPaymentSdk} obj Optional instance to populate.
   * @return {module:model/UnifiedriskPaymentSdk} The populated <code>UnifiedriskPaymentSdk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('encryptedData')) {
        obj['encryptedData'] = ApiClient.convertToType(data['encryptedData'], 'String');
      }
      if (data.hasOwnProperty('ephemPubKey')) {
        obj['ephemPubKey'] = ApiClient.convertToType(data['ephemPubKey'], 'String');
      }
      if (data.hasOwnProperty('appId')) {
        obj['appId'] = ApiClient.convertToType(data['appId'], 'String');
      }
      if (data.hasOwnProperty('referenceNumber')) {
        obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
      }
      if (data.hasOwnProperty('maxTimeout')) {
        obj['maxTimeout'] = ApiClient.convertToType(data['maxTimeout'], 'String');
      }
      if (data.hasOwnProperty('flowType')) {
        obj['flowType'] = ApiClient.convertToType(data['flowType'], 'String');
      }
      if (data.hasOwnProperty('defaultSdkType')) {
        obj['defaultSdkType'] = ApiClient.convertToType(data['defaultSdkType'], 'String');
      }
    }
    return obj;
  }

  /**
   * SDK type used for the 3DS or payment authentication flow (e.g., DEFAULT_BROWSER, NATIVE_APP, THREEDS_SDK). Determines the authentication method and data format
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Encrypted device data payload collected by the 3DS SDK from the cardholder's device, used for device-based risk assessment during authentication
   * @member {String} encryptedData
   */
  exports.prototype['encryptedData'] = undefined;
  /**
   * Ephemeral public key generated by the 3DS SDK during the authentication session, used for secure key exchange in the SDK authentication flow
   * @member {String} ephemPubKey
   */
  exports.prototype['ephemPubKey'] = undefined;
  /**
   * Unique identifier for the merchant's mobile application used for 3DS SDK authentication, registered with the 3DS directory server
   * @member {String} appId
   */
  exports.prototype['appId'] = undefined;
  /**
   * 3DS SDK transaction reference number used to correlate the SDK authentication session with the payment transaction
   * @member {String} referenceNumber
   */
  exports.prototype['referenceNumber'] = undefined;
  /**
   * Maximum time in minutes allowed for the 3DS SDK authentication process to complete before the session expires and authentication fails
   * @member {String} maxTimeout
   */
  exports.prototype['maxTimeout'] = undefined;
  /**
   * The 3DS authentication flow type used in this transaction (e.g., FRICTIONLESS, CHALLENGE, DECOUPLED). Impacts user experience and liability shift
   * @member {String} flowType
   */
  exports.prototype['flowType'] = undefined;
  /**
   * The default SDK type configured for this merchant or application when no explicit SDK type is specified in the request
   * @member {String} defaultSdkType
   */
  exports.prototype['defaultSdkType'] = undefined;



  return exports;
}));


