/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.UnifiedriskMerchantAddress = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UnifiedriskMerchantAddress model module.
   * @module model/UnifiedriskMerchantAddress
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>UnifiedriskMerchantAddress</code>.
   * @alias module:model/UnifiedriskMerchantAddress
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>UnifiedriskMerchantAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnifiedriskMerchantAddress} obj Optional instance to populate.
   * @return {module:model/UnifiedriskMerchantAddress} The populated <code>UnifiedriskMerchantAddress</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('addressLine1')) {
        obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
      }
      if (data.hasOwnProperty('addressLine2')) {
        obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
      }
      if (data.hasOwnProperty('addressLine3')) {
        obj['addressLine3'] = ApiClient.convertToType(data['addressLine3'], 'String');
      }
      if (data.hasOwnProperty('addressType')) {
        obj['addressType'] = ApiClient.convertToType(data['addressType'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('administrativeArea')) {
        obj['administrativeArea'] = ApiClient.convertToType(data['administrativeArea'], 'String');
      }
      if (data.hasOwnProperty('fullAddress')) {
        obj['fullAddress'] = ApiClient.convertToType(data['fullAddress'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('postalCode')) {
        obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
      }
      if (data.hasOwnProperty('locality')) {
        obj['locality'] = ApiClient.convertToType(data['locality'], 'String');
      }
      if (data.hasOwnProperty('countrySubDivision')) {
        obj['countrySubDivision'] = ApiClient.convertToType(data['countrySubDivision'], 'String');
      }
      if (data.hasOwnProperty('townName')) {
        obj['townName'] = ApiClient.convertToType(data['townName'], 'String');
      }
    }
    return obj;
  }

  /**
   * Address line 1
   * @member {String} addressLine1
   */
  exports.prototype['addressLine1'] = undefined;
  /**
   * Address line 2
   * @member {String} addressLine2
   */
  exports.prototype['addressLine2'] = undefined;
  /**
   * Address line 3
   * @member {String} addressLine3
   */
  exports.prototype['addressLine3'] = undefined;
  /**
   * Identifies the nature of the postal address. Examples are \"Home\" or \"Work\".
   * @member {String} addressType
   */
  exports.prototype['addressType'] = undefined;
  /**
   * Nation with its own government, country code in ISO 3166 apha-3 format
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * Identifies a subdivision of a country such as state, region, county
   * @member {String} administrativeArea
   */
  exports.prototype['administrativeArea'] = undefined;
  /**
   * Full string containing all submitted address components.
   * @member {String} fullAddress
   */
  exports.prototype['fullAddress'] = undefined;
  /**
   * Latitude of the address
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * Longitude of the address
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail
   * @member {String} postalCode
   */
  exports.prototype['postalCode'] = undefined;
  /**
   * Name of a built-up area, with defined boundaries, and a local government.
   * @member {String} locality
   */
  exports.prototype['locality'] = undefined;
  /**
   * Country sub-division code (e.g., state or province) for the merchant's registered address, expressed as an ISO 3166-2 subdivision code (e.g., GB-ENG, US-CA)
   * @member {String} countrySubDivision
   */
  exports.prototype['countrySubDivision'] = undefined;
  /**
   * Town or city name of the merchant's registered address. Used alongside locality for precise address matching and geolocation
   * @member {String} townName
   */
  exports.prototype['townName'] = undefined;



  return exports;
}));


