/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.UpdateAsymKeysRequest = factory(root.CyberSource.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdateAsymKeysRequest model module.
   * @module model/UpdateAsymKeysRequest
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>UpdateAsymKeysRequest</code>.
   * @alias module:model/UpdateAsymKeysRequest
   * @class
   * @param status {String} Status can be active/inactive
   * @param organizationId {String} Organization Id
   */
  var exports = function(status, organizationId) {
    var _this = this;

    _this['status'] = status;
    _this['organizationId'] = organizationId;
  };

  /**
   * Constructs a <code>UpdateAsymKeysRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateAsymKeysRequest} obj Optional instance to populate.
   * @return {module:model/UpdateAsymKeysRequest} The populated <code>UpdateAsymKeysRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('organizationId')) {
        obj['organizationId'] = ApiClient.convertToType(data['organizationId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Status can be active/inactive
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Organization Id
   * @member {String} organizationId
   */
  exports.prototype['organizationId'] = undefined;



  return exports;
}));


