/**
 * CyberSource Flex API
 * Simple PAN tokenization service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse4006', 'model/InlineResponse502', 'model/OctCreatePaymentRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse4006'), require('../model/InlineResponse502'), require('../model/OctCreatePaymentRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }
    root.CyberSource.ProcessAPayoutApi = factory(root.CyberSource.ApiClient, root.CyberSource.InlineResponse4006, root.CyberSource.InlineResponse502, root.CyberSource.OctCreatePaymentRequest);
  }
}(this, function(ApiClient, InlineResponse4006, InlineResponse502, OctCreatePaymentRequest) {
  'use strict';

  /**
   * ProcessAPayout service.
   * @module api/ProcessAPayoutApi
   * @version 0.0.1
   */

  /**
   * Constructs a new ProcessAPayoutApi. 
   * @alias module:api/ProcessAPayoutApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
    var exports = function(configObject, apiClient = undefined) {
    this.apiClient = apiClient || ApiClient.instance;

    this.apiClient.setConfiguration(configObject);


    /**
     * Callback function to receive the result of the octCreatePayment operation.
     * @callback module:api/ProcessAPayoutApi~octCreatePaymentCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Process a Payout
     * Send funds from a selected funding source to a designated credit/debit card account or a prepaid card using an Original Credit Transaction (OCT). 
     * @param {module:model/OctCreatePaymentRequest} octCreatePaymentRequest 
     * @param {module:api/ProcessAPayoutApi~octCreatePaymentCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.octCreatePayment = function(octCreatePaymentRequest, callback) {
      var postBody = octCreatePaymentRequest;

      // verify the required parameter 'octCreatePaymentRequest' is set
      if (octCreatePaymentRequest === undefined || octCreatePaymentRequest === null) {
        throw new Error("Missing the required parameter 'octCreatePaymentRequest' when calling octCreatePayment");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/hal+json;charset=utf-8'];
      var returnType = null;

      return this.apiClient.callApi(
        '/pts/v2/payouts/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
