/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.38
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CyberSource);
  }
}(this, function(expect, CyberSource) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CyberSource.Iccv1mppcredentialsChallenge();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Iccv1mppcredentialsChallenge', function() {
    it('should create an instance of Iccv1mppcredentialsChallenge', function() {
      // uncomment below and update the code to test Iccv1mppcredentialsChallenge
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be.a(CyberSource.Iccv1mppcredentialsChallenge);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property realm (base name: "realm")', function() {
      // uncomment below and update the code to test the property realm
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property acceptedNetworks (base name: "acceptedNetworks")', function() {
      // uncomment below and update the code to test the property acceptedNetworks
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property merchantName (base name: "merchantName")', function() {
      // uncomment below and update the code to test the property merchantName
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

    it('should have the property encryptionJwk (base name: "encryption_jwk")', function() {
      // uncomment below and update the code to test the property encryptionJwk
      //var instane = new CyberSource.Iccv1mppcredentialsChallenge();
      //expect(instance).to.be();
    });

  });

}));
