/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CyberSource);
  }
}(this, function(expect, CyberSource) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting', function() {
    it('should create an instance of PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting', function() {
      // uncomment below and update the code to test PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be.a(CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting);
    });

    it('should have the property standardEntryClassCodes (base name: "standardEntryClassCodes")', function() {
      // uncomment below and update the code to test the property standardEntryClassCodes
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property enableHold (base name: "enableHold")', function() {
      // uncomment below and update the code to test the property enableHold
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property monthlyTotalTransactionAmountLimit (base name: "monthlyTotalTransactionAmountLimit")', function() {
      // uncomment below and update the code to test the property monthlyTotalTransactionAmountLimit
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property holdingDays (base name: "holdingDays")', function() {
      // uncomment below and update the code to test the property holdingDays
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property enableCredits (base name: "enableCredits")', function() {
      // uncomment below and update the code to test the property enableCredits
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property transactionAmountLimit (base name: "transactionAmountLimit")', function() {
      // uncomment below and update the code to test the property transactionAmountLimit
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property riskReserveMethod (base name: "riskReserveMethod")', function() {
      // uncomment below and update the code to test the property riskReserveMethod
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property riskReserveRate (base name: "riskReserveRate")', function() {
      // uncomment below and update the code to test the property riskReserveRate
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property riskReserveTargetAmount (base name: "riskReserveTargetAmount")', function() {
      // uncomment below and update the code to test the property riskReserveTargetAmount
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

    it('should have the property solutionOrganizationId (base name: "solutionOrganizationId")', function() {
      // uncomment below and update the code to test the property solutionOrganizationId
      //var instane = new CyberSource.PaymentProductsECheckConfigurationInformationConfigurationsUnderwriting();
      //expect(instance).to.be();
    });

  });

}));
