/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CyberSource);
  }
}(this, function(expect, CyberSource) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportingV3ReportDefinitionsGet200ResponseReportDefinitions', function() {
    it('should create an instance of ReportingV3ReportDefinitionsGet200ResponseReportDefinitions', function() {
      // uncomment below and update the code to test ReportingV3ReportDefinitionsGet200ResponseReportDefinitions
      //var instane = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
      //expect(instance).to.be.a(CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
      //expect(instance).to.be();
    });

    it('should have the property reportDefinitionId (base name: "reportDefinitionId")', function() {
      // uncomment below and update the code to test the property reportDefinitionId
      //var instane = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
      //expect(instance).to.be();
    });

    it('should have the property reportDefintionName (base name: "reportDefintionName")', function() {
      // uncomment below and update the code to test the property reportDefintionName
      //var instane = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
      //expect(instance).to.be();
    });

    it('should have the property supportedFormats (base name: "supportedFormats")', function() {
      // uncomment below and update the code to test the property supportedFormats
      //var instane = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new CyberSource.ReportingV3ReportDefinitionsGet200ResponseReportDefinitions();
      //expect(instance).to.be();
    });

  });

}));
