name: Node workflow to run Node REST Samples
on:
  push:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-node'
  SAMPLE_FOLDER: 'cybersource-rest-samples-node'
  NPM_CLIENT_FOLDER : 'npm-client-sdk'
jobs:
    run-samples:
        defaults:
            run:
              shell: bash
        strategy:
            matrix:
              operating-system: [ubuntu-latest,macos-latest,windows-latest]
              node-ver: [14.x,15.x,16.x,17.x,18.x,19.x,20.x,21.x,22.x]
        runs-on: ${{matrix.operating-system}}
        continue-on-error: true
        steps:
            - name: Making separate folders
              run: |
                rm -rf $CLIENT_FOLDER
                rm -rf $SAMPLE_FOLDER
                mkdir $CLIENT_FOLDER $SAMPLE_FOLDER
            - name: Adding client
              uses: actions/checkout@v4
              with:
                path: ${{env.CLIENT_FOLDER}}
                ref: 'adding-workflows'
            - name: Adding sample
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/${{env.SAMPLE_FOLDER}}'
                ref: 'testing-branch'
                path: ${{env.SAMPLE_FOLDER}}
            - name: Installing Required Node Version on the Machine
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-ver}}
            - name: Build the Project
              run: |
                cd $CLIENT_FOLDER
                npm install
                # npm pack
                # rm -rf ../$NPM_CLIENT_FOLDER
                # mkdir ../$NPM_CLIENT_FOLDER
                # PACKAGE_VERSION=\$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
                # tar -xvzf "cybersource-rest-client-$PACKAGE_VERSION.tgz" -C ../$NPM_CLIENT_FOLDER
                # cd ../$NPM_CLIENT_FOLDER/package
                npm link
                cd ../$SAMPLE_FOLDER
                npm link cybersource-rest-client
                npm install
                bash ./sample_code_runner.sh
            # - name: Getting the Validation files
            #   uses: actions/checkout@v4
            #   with:
            #     repository: 'CyberSource/cybersource-rest-samples-python'
            #     ref: 'testing-branch'
            #     path: ${{env.SAMPLE_FOLDER}}
            #     sparse-checkout: |
            #       Validation
            # - name: Generating the Report
            #   run:
            #     pwd
            #     ls
                # cd $SAMPLE_FOLDER
            #     pip install json2html
            #     pip install xhtml2pdf
            #     pip install bs4
            #     cd Validation
            #     python sample_code_log_processor.py -l ../../$SAMPLE_FOLDER/output.log -o ../../$SAMPLE_FOLDER/python_actual_results.json
            #     python response_code_validator.py -e ExpectedResults/python_expected_results.json -a ../../$SAMPLE_FOLDER/python_actual_results.json -o python_validation_results.json
            #     python json_to_prettified_html.py -i python_validation_results.json -o python_validation_results.html

            # - name: Upload the log files and report pdf
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: log-files-${{matrix.operating-system}}
            #     path: |
            #       ${{env.SAMPLE_FOLDER}}/output.log
            


#                   node-sdk
#    1. node client sdk
#    2. sample sdk
#    3. NpmClientSdk

# go to node client folder
# npm install
# npm pack
# rm -rf ../NpmClientSdk
# mkdir ../NpmClientSdk
# PACKAGE_VERSION=\$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
# tar -xvzf "cybersource-rest-client-$PACKAGE_VERSION.tgz" -C ../NpmClientSdk
# cd ../NpmClientSdk/package
# npm link
# cd ../../cybersource-rest-samples-node
# npm link cybersource-rest-client
# npm install




