name:  workflow for cybs rest client node sdk to run samples
on:
  push:
  pull_request: 
  workflow_dispatch:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-node'
  SAMPLE_FOLDER: 'cybersource-rest-samples-node'
  NPM_CLIENT_FOLDER : 'npm-client-sdk'
jobs:
    workflow-job:
        defaults:
            run:
              shell: bash
        strategy:
            fail-fast: false
            matrix:
              operating-system: [ubuntu-latest,macos-latest,windows-latest]
              node-ver: [14.x,16.x,17.x,18.x,19.x,20.x,21.x,22.x]  # Axios Doesn't support node version 15
              exclude:
                - operating-system: macos-latest  # No Node 14 image is there for the arm64 architecture of mac
                  node-ver: 14.x
              include:
                - operating-system: macos-13  # No Node 14 image is there for the arm64 architecture of mac
                  node-ver: 14.x
        runs-on: ${{matrix.operating-system}}
        steps:
            - name: Creating separate folders for checkout repos
              run: |
                rm -rf $CLIENT_FOLDER
                rm -rf $SAMPLE_FOLDER
                mkdir $CLIENT_FOLDER $SAMPLE_FOLDER
            - name: Checkout cybersource-rest-client-node repo
              uses: actions/checkout@v4
              with:
                path: ${{env.CLIENT_FOLDER}}
                ref: 'adding-workflows'
            - name: Checkout cybersource-rest-samples-node repo
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/${{env.SAMPLE_FOLDER}}'
                ref: 'testing-branch'
                path: ${{env.SAMPLE_FOLDER}}
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-ver}}
            - name: Building the projects and running the Test Cases
              run: |
                cd $CLIENT_FOLDER
                npm install
                npm pack
                rm -rf ../$NPM_CLIENT_FOLDER
                mkdir ../$NPM_CLIENT_FOLDER
                PACKAGE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
                tar -xvzf "cybersource-rest-client-$PACKAGE_VERSION.tgz" -C ../$NPM_CLIENT_FOLDER
                cd ../$NPM_CLIENT_FOLDER/package
                npm link
                cd ../../$SAMPLE_FOLDER
                npm link cybersource-rest-client
                npm install
                bash ./sample_code_runner.sh
            - name: Setup Python v3.12 for report generation only
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Installing required python libraries and running the python programs to generate pdf report
              run: |
                cd $SAMPLE_FOLDER
                python -m pip install --upgrade pip
                pip install json2html
                pip install xhtml2pdf
                pip install bs4
                cd Validation
                python sample_code_log_processor.py -l ../../$SAMPLE_FOLDER/output.log -o ../../$SAMPLE_FOLDER/python_actual_results.json
                python response_code_validator.py -e ExpectedResults/python_expected_results.json -a ../../$SAMPLE_FOLDER/python_actual_results.json -o python_validation_results.json
                python json_to_prettified_html.py -i python_validation_results.json -o python_validation_results.html
            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              with:
                name: log-files-${{matrix.operating-system}}-ver${{matrix.node-ver}}
                path: |
                  ${{env.SAMPLE_FOLDER}}/Validation/python_validation_results.pdf
